// Hotel Info Action Types
export const FETCHING_HOTEL_INFO = 'FETCHING_HOTEL_INFO';
export const GET_HOTEL_INFO_SUCCESS = 'GET_HOTEL_INFO_SUCCESS';
export const GET_HOTEL_INFO_ERROR = 'GET_HOTEL_INFO_ERROR';

// User Info Action Types
export const FETCHING_USER_INFO = 'FETCHING_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';

// Chats Action Types
export const FETCHING_CHATS = 'FETCHING_CHATS';
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
export const GET_CHATS_ERROR = 'GET_CHATS_ERROR';

// Notifications Action Types
export const FETCHING_NOTIFICATIONS = 'FETCHING_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR';

// Amenity Action Types
export const FETCHING_AMENITY_RESOURCE = 'FETCHING_AMENITY_RESOURCE';
export const FETCHING_AMENITY_RESOURCES = 'FETCHING_AMENITY_RESOURCES';
export const FETCHING_AMENITY_CATEGORIES = 'FETCHING_AMENITY_CATEGORIES';
export const FETCHING_AMENITY_CATEGORY= 'FETCHING_AMENITY_CATEGORY';

export const GET_AMENITY_RESOURCES_SUCCESS = 'GET_AMENITY_RESOURCES_SUCCESS';
export const GET_AMENITY_RESOURCES_FAILED = 'GET_AMENITY_RESOURCES_FAILED';
export const GET_CURRENT_AMENITY_RESOURCE_SUCCESS = 'GET_CURRENT_AMENITY_RESOURCE_SUCCESS';
export const GET_CURRENT_AMENITY_RESOURCE_FAILED = 'GET_CURRENT_AMENITY_RESOURCE_FAILED';
export const GET_AMENITY_CATEGORY_SUCCESS = 'GET_AMENITY_CATEGORY_SUCCESS';
export const GET_AMENITY_CATEGORY_FAILED = 'GET_AMENITY_CATEGORY_FAILED';
export const GET_AMENITY_CATEGORIES_SUCCESS = 'GET_AMENITY_CATEGORIES_SUCCESS';
export const GET_AMENITY_CATEGORIES_FAILED = 'GET_AMENITY_CATEGORIES_FAILED';

export const SET_CURRENT_AMENITY_RESOURCE_SUCCESS = 'SET_CURRENT_AMENITY_RESOURCE_SUCCESS';
export const SET_CURRENT_AMENITY_CATEGORY_SUCCESS = 'SET_CURRENT_AMENITY_CATEGORY_SUCCESS';

export const INITIALIZE_CURRENT_AMENITY_RESOURCE = 'INITIALIZE_CURRENT_AMENITY_RESOURCE';
export const INITIALIZE_CURRENT_AMENITY_CATEGORY = 'INITIALIZE_CURRENT_AMENITY_CATEGORY';

// Gift Shop Action Types
export const FETCHING_GIFT_SHOP= 'FETCHING_GIFT_SHOP';
export const FETCHING_GIFT_SHOP_RESOURCE = 'FETCHING_GIFT_SHOP_RESOURCE';
export const FETCHING_GIFT_SHOP_CATEGORIES = 'FETCHING_GIFT_SHOP_CATEGORIES';
export const FETCHING_GIFT_SHOP_CATEGORY= 'FETCHING_GIFT_SHOP_CATEGORY';
export const FETCHING_GIFT_SHOP_RESOURCES= 'FETCHING_GIFT_SHOP_RESOURCES';

export const GET_CURRENT_GIFT_SHOP_RESOURCE_SUCCESS = 'GET_CURRENT_GIFT_SHOP_RESOURCE_SUCCESS';
export const GET_CURRENT_GIFT_SHOP_RESOURCE_FAILED = 'GET_CURRENT_GIFT_SHOP_RESOURCE_FAILED';
export const GET_CURRENT_GIFT_SHOP_CATEGORY_SUCCESS = 'GET_CURRENT_GIFT_SHOP_CATEGORY_SUCCESS';
export const GET_CURRENT_GIFT_SHOP_CATEGORY_FAILED = 'GET_CURRENT_GIFT_SHOP_CATEGORY_FAILED';

export const GET_GIFT_SHOP_CATEGORIES_SUCCESS = 'GET_GIFT_SHOP_CATEGORIES_SUCCESS';
export const GET_GIFT_SHOP_CATEGORIES_FAILED = 'GET_GIFT_SHOP_CATEGORIES_FAILED';

export const GET_GIFT_SHOP_RESOURCES_SUCCESS = 'GET_GIFT_SHOP_RESOURCES_SUCCESS';
export const GET_GIFT_SHOP_RESOURCES_FAILED = 'GET_GIFT_SHOP_RESOURCES_FAILED';

export const SET_CURRENT_GIFT_SHOP_CATEGORY_SUCCESS = 'SET_CURRENT_GIFT_SHOP_CATEGORY_SUCCESS';
export const SET_CURRENT_GIFT_SHOP_RESOURCE_SUCCESS = 'SET_CURRENT_GIFT_SHOP_RESOURCE_SUCCESS';

export const INITIALIZE_GIFT_SHOP = 'INITIALIZE_GIFT_SHOP';
export const INITIALIZE_GIFT_SHOP_RESOURCE = 'INITIALIZE_GIFT_SHOP_RESOURCE';
export const INITIALIZE_GIFT_SHOP_CATEGORY = 'INITIALIZE_GIFT_SHOP_CATEGORY';

// Search action types

export const SEARCHING_FOR_RESOURCES = 'SEARCHING_FOR_RESOURCES';
export const SEARCHING_FOR_RESOURCES_FINISHED = 'SEARCHING_FOR_RESOURCES_FINISHED';

